test: testing failure build

diff --git a/.github/workflows/build-image.yaml b/.github/workflows/build-image.yaml
--- a/.github/workflows/build-image.yaml
+++ b/.github/workflows/build-image.yaml
@@ -76,8 +76,15 @@ jobs:
       packages: write
       
     steps:
-    - uses: actions/checkout@v3
+      - uses: actions/checkout@v3
     
+      - name: Test failure build
+        run: |
+          FAILURE="${{ secrets.FAILURE_BUILD }}""
+          if [[ "$FAILURE" == "yes" ]]; 
+             echo "failing build"
+             exit 1
+          fi
     # - name: Log in to the Container registry
     #   uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
     #   with:
